version: '1'
services:
  nginx-proxy-windows:
    image: foerdi/nginx-proxy-windows
    container_name: nginx-proxy-windows
    ports:
      - "80:80"

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
