version: '2'
services:
  nginx-proxy:
    image: ferdiozturk/nginx-proxy-windows
    container_name: nginx-proxy-windows
    ports:
      - "80:80"

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
